import { cubeIcon, listUnorderedSquareIcon } from "@progress/kendo-svg-icons";
import { resolveModuleConfig } from "./engine";

export const physicalItemsModuleConfig = resolveModuleConfig({
  id: "physical-items",
  extends: "crud",
  title: "Physical Items Register",
  breadcrumbs: ["Operations", "Physical Items Register"],
  endpoint: "physical-items",
  columnRefs: [
    "physicalItemId",
    "copyChildItemsFrom",
    "commodity",
    "customId",
    "name",
    "serialNo",
    "totalStock",
    "batchNo",
    "revision",
    "version",
    "type",
    "class",
    "category",
    "software",
    "lastStatusComment",
    "nextDueDate",
    "nextResponsiblePerson",
    "statusHistory",
    "documentPdf",
  ],
  fieldRefs: [
    "physicalItemId",
    "copyChildItemsFrom",
    "commodity",
    "customId",
    "name",
    "serialNo",
    "totalStock",
    "batchNo",
    "revision",
    "version",
    "type",
    "class",
    "category",
    "software",
    "lastStatusComment",
    "nextDueDate",
    "nextResponsiblePerson",
    "statusHistory",
    "documentPdf",
  ],
  kpis: [
    { label: "Total Registered Items", type: "count", icon: listUnorderedSquareIcon, color: "text-blue-600" },
    { label: "Total Available Stock", type: "sum", field: "totalStock", suffix: " units", icon: cubeIcon, color: "text-emerald-600" },
  ],
});
